version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 221047265242.dkr.ecr.ap-southeast-1.amazonaws.com/waizly-ecr
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - docker build .          
      - docker build -t anjasmara_service_users_v1:latest .
      - docker tag anjasmara_service_users_v1:latest 221047265242.dkr.ecr.ap-southeast-1.amazonaws.com/waizly-ecr/anjasmara_service_users_v1:latest

  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push 221047265242.dkr.ecr.ap-southeast-1.amazonaws.com/waizly-ecr/anjasmara_service_users_v1:latest
      - printf '[{"name":"tes-app","imageUri":"%s"}]' 221047265242.dkr.ecr.ap-southeast-1.amazonaws.com/waizly-ecr/anjasmara_service_users_v1:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - kube-manifests/*