version: 0.2

phases:
  install:
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.15.10/2020-02-22/bin/darwin/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
      #- aws eks update-kubeconfig --name EKS-Cluster --region ap-southeast-1 --profile anotheracc
      #- cat ~/.kube/config
      #4. Set the image tag
      - export TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
  pre_build:
    commands:
      #- "mkdir ~/.kube/"
      #- "cp config-$ENV ~/.kube/config"
      - TAG="$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 221047265242.dkr.ecr.ap-southeast-1.amazonaws.com
      # - echo "Update Kube Config"      
      #- aws eks update-kubeconfig --name EKS-Cluster --region ap-southeast-1
  build:
    commands:
      - docker build . -t $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION -f anjasmara-service-users-v1/
      - docker tag docker tag $IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION 221047265242.dkr.ecr.ap-southeast-1.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push 221047265242.dkr.ecr.ap-southeast-1.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
      #- export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      #- export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - echo "Apply changes to kube manifests"            
      - kubectl apply -f kube-manifests/*
      - printf '[{"name":"tes-app","imageUri":"%s"}]' 221047265242.dkr.ecr.ap-southeast-1.amazonaws.com/anjasmara_service_users_v1:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - kube-manifests/*