
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anjasmara-service-users-deployment
  labels:
    app: anjasmara-service-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anjasmara-service-users
  template:
    metadata:
      labels:
        app: anjasmara-service-users 
    spec:
      containers:
      - name: anjasmara-service-users
        image: mulki12/anjasmara_service_users_v1:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: anjasmara-service-users
spec:
  selector:
    app: anjasmara-service-users 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31110
