
   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: anjasmara_service_users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anjasmara_service_users
  template:
    metadata:
      labels:
        app: anjasmara_service_users 
    spec:
      containers:
      - name: anjasmara_service_users
        image: mulki12/anjasmara_service_users:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: anjasmara_service_users
spec:
  selector:
    app: anjasmara_service_users 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31110
