apiVersion: apps/v1
kind: Deployment
metadata:
  name: anjasmara-service-users-v1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: anjasmara-service-users-v1
  template:
    metadata:
      labels:
        app: anjasmara-service-users-v1
    spec:
      containers:
      - image: mulki12/anjasmara_service_users_v1
        name: anjasmara-service-users-v1
        ports:
        - containerPort: 3000
